stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  script:
  - npm install
  - npm run build
  - mv dist public
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
    key: project

deploy_github:
  dependencies:
    - build
  stage: deploy
  only:
  - master
  - hmac
  script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > deploy.key
  - chmod 0600 deploy.key
  - ssh-add deploy.key
  - git clone git@github.com:SilverBlog/silvercreator.github.io.git silvercreator
  - cp -r dist/* silvercreator/
  #- git push --set-upstream git@github.com:SilverBlog/silvercreator.github.io.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
  - git push --set-upstream git@github.com:SilverBlog/silvercreator.github.io.git HEAD:refs/heads/master

release_github:
  stage: deploy
  only:
  - master
  script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" > deploy.key
  - chmod 0600 deploy.key
  - ssh-add deploy.key
  - git push --set-upstream git@github.com:SilverBlog/silvercreator.github.io.git HEAD:refs/heads/$CI_COMMIT_REF_NAME
