stages:
  - build
  - deploy

pages:
  stage: build
  image: node:latest
  script:
  - npm install
  - npm run build
  - mv dist public
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
    key: project

release_github:
  image: docker.reallserver.cn/public/docker-git
  stage: push
  only:
  - master
  script:
  - git push --set-upstream https://${github_key}@github.com/SilverBlogTeam/silvercreator.git HEAD:master
